/**
 * Dutch football sentiment lexicon.
 *
 * Why hand-built rather than an off-the-shelf model:
 *  - General Dutch sentiment sets (Pattern, DuOMan) are trained on product
 *    reviews. They score "dramatisch" and "kansloos" as mild, when in a football
 *    context they are the strongest negatives a fan uses.
 *  - Football words are polarity-flipped relative to normal Dutch. "Hard" is
 *    praise for a defender, "makkelijk" is an insult, "rustig" is a compliment
 *    for a keeper and a complaint about a midfield.
 *  - English models score Dutch text near zero, which silently produces a flat
 *    neutral chart that looks plausible and is entirely meaningless.
 *
 * Weights run -3 (worst thing a fan says) to +3 (title-winning euphoria).
 * Keys are lowercase; matching is done on stems so "dramatische" hits
 * "dramatisch". Multi-word entries are matched as phrases before single tokens.
 */

export const LEXICON: Record<string, number> = {
  // --- catastrophe ---------------------------------------------------------
  dramatisch: -3,
  kansloos: -3,
  wanprestatie: -3,
  vernedering: -3,
  vernederend: -3,
  afgang: -3,
  blamage: -3,
  schande: -3,
  schandalig: -3,
  waardeloos: -3,
  belabberd: -3,
  bagger: -3,
  dieptepunt: -3,
  rampzalig: -3,
  ramp: -2.5,
  debacle: -3,
  fiasco: -3,
  mislukking: -3,
  mislukt: -2.5,
  abominabel: -3,
  erbarmelijk: -3,
  gênant: -2.5,
  beschamend: -2.5,
  triest: -2.5,
  treurig: -2.5,
  hopeloos: -2.5,
  uitzichtloos: -2.5,

  // --- crisis / institutional ---------------------------------------------
  crisis: -2.5,
  chaos: -2.5,
  onrust: -2,
  ruzie: -2,
  conflict: -2,
  rel: -2,
  ontslag: -2,
  ontslagen: -2,
  opstappen: -1.5,
  vertrokken: -1,
  degradatie: -2.5,
  degraderen: -2.5,
  wanbeleid: -3,
  puinhoop: -3,
  zooitje: -2.5,

  // --- ordinary negative ---------------------------------------------------
  slecht: -2,
  zwak: -2,
  teleurstellend: -2,
  teleurstelling: -2,
  teleurgesteld: -2,
  tegenvallend: -2,
  tegenvaller: -2,
  matig: -1.5,
  moeizaam: -1.5,
  pijnlijk: -2,
  zorgelijk: -1.5,
  zorgen: -1.5,
  probleem: -1.5,
  problemen: -1.5,
  kritiek: -1.5,
  twijfel: -1,
  twijfels: -1.25,
  onzeker: -1.25,
  blunder: -2.5,
  fout: -1.25,
  fouten: -1.5,
  flop: -2.5,
  faalt: -2.5,
  falen: -2.5,
  gefaald: -2.5,
  verlies: -1.5,
  verloren: -1.5,
  nederlaag: -2,
  uitgeschakeld: -2.5,
  uitschakeling: -2.5,
  boos: -2,
  woedend: -2.5,
  woede: -2.25,
  gefrustreerd: -2,
  frustratie: -2,
  irritatie: -1.75,
  ergernis: -1.75,
  lusteloos: -2.25,
  moedeloos: -2.25,
  zielloos: -2.5,
  gelaten: -1.5,
  stroef: -1.5,
  rommelig: -1.75,
  slordig: -1.75,
  naïef: -1.5,
  passief: -1.5,
  weggegeven: -2,
  weggeven: -1.75,
  verspild: -2,
  gemist: -1,
  missen: -1,
  mist: -1,

  // --- injuries ------------------------------------------------------------
  blessure: -1.5,
  geblesseerd: -1.5,
  blessures: -1.75,
  kruisband: -2.5,
  hamstring: -1.5,
  revalidatie: -1,
  uitgevallen: -1.5,

  // --- vulgar / terrace register ------------------------------------------
  // Fans reach for these constantly; omitting them costs a lot of real signal.
  kut: -3,
  klote: -3,
  waardeloze: -3,
  brak: -2,
  schandalige: -3,

  // --- ordinary positive ---------------------------------------------------
  goed: 1.5,
  goede: 1.5,
  sterk: 2,
  sterke: 2,
  mooi: 1.5,
  mooie: 1.5,
  knap: 2,
  knappe: 2,
  verdiend: 1.5,
  verdiende: 1.5,
  degelijk: 1.25,
  solide: 1.75,
  stabiel: 1.5,
  volwassen: 1.75,
  gretig: 1.75,
  scherp: 1.75,
  fris: 1.5,
  energiek: 1.75,
  hoopvol: 1.5,
  hoop: 1.5,
  vertrouwen: 1.5,
  herstel: 1.5,
  opleving: 2,
  ommekeer: 2,
  comeback: 2.5,

  // --- strong positive -----------------------------------------------------
  geweldig: 3,
  fantastisch: 3,
  briljant: 3,
  subliem: 3,
  schitterend: 2.75,
  prachtig: 2.5,
  prachtige: 2.5,
  heerlijk: 2.5,
  genieten: 2.5,
  genoten: 2.5,
  genot: 2.5,
  klasse: 2.5,
  klassepot: 3,
  uitstekend: 2.5,
  indrukwekkend: 2.5,
  imponerend: 2.5,
  dominant: 2,
  overtuigend: 2,
  meesterlijk: 3,
  magistraal: 3,
  fenomenaal: 3,
  ijzersterk: 2.75,
  oppermachtig: 2.75,
  trots: 2,
  blij: 2,
  euforie: 2.75,
  euforisch: 2.75,
  opluchting: 1.5,

  // --- outcomes ------------------------------------------------------------
  winst: 1.5,
  wint: 1.5,
  winnen: 1.25,
  gewonnen: 1.5,
  koploper: 2,
  koppositie: 2,
  prima: 1.75,
  puik: 2,
  overwinning: 2,
  zege: 2,
  zegereeks: 2.5,
  kampioen: 3,
  kampioenschap: 3,
  titel: 2,
  landstitel: 2.75,
  beker: 1.75,
  goal: 1,
  doelpunt: 1,
  prachtgoal: 3,
  wereldgoal: 3,
  hattrick: 2.5,
  held: 2.5,
  uitblinker: 2.5,
  matchwinner: 2.25,
  talent: 1.5,
  toptalent: 2.25,
  parel: 2.25,

  // --- terrace praise ------------------------------------------------------
  chapeau: 2.5,
  hulde: 2.5,
  respect: 1.75,
  top: 2,
  topper: 2,
  topwedstrijd: 2.5,
  geniaal: 3,
  legendarisch: 2.75,
};

/** Phrases scored as a unit; matched before single-token lookup. */
export const PHRASES: Record<string, number> = {
  'om te janken': -3,
  'niet om aan te zien': -3,
  'geen niveau': -2.5,
  'geen enkele kans': -2.5,
  'geen schijn van kans': -2.5,
  'de weg kwijt': -2.5,
  'op sterven na dood': -2.75,
  'door het putje': -2.75,
  'van geen kanten': -2.5,
  'niet best': -1.75,
  'onder de maat': -2.25,
  'ver onder de maat': -3,
  'geen gezicht': -2.5,
  'te kort': -1.5,
  'tekort geschoten': -2,
  'in de as gelegd': -2.5,
  'petje af': 2.5,
  'klasse apart': 3,
  'genieten geblazen': 2.75,
  'wat een goal': 2.75,
  'wat een wedstrijd': 2.25,
  'op rolletjes': 2.25,
  'ouderwets genieten': 2.75,
  'de weg omhoog': 2,
  'goed op dreef': 2.25,
  'in vorm': 1.75,
  'weer even wakker': 1.5,
};

/** Multipliers applied to the next scored term. */
export const INTENSIFIERS: Record<string, number> = {
  heel: 1.5,
  zeer: 1.6,
  erg: 1.5,
  ontzettend: 1.9,
  enorm: 1.8,
  echt: 1.4,
  totaal: 1.9,
  compleet: 1.8,
  volledig: 1.7,
  absoluut: 1.7,
  volstrekt: 1.8,
  mega: 1.8,
  super: 1.7,
  ongelooflijk: 1.8,
  onwijs: 1.7,
  bijzonder: 1.5,
  behoorlijk: 1.3,
  flink: 1.4,
  keihard: 1.6,
  verschrikkelijk: 1.8,
  dood: 1.6,
};

export const DIMINISHERS: Record<string, number> = {
  beetje: 0.5,
  enigszins: 0.5,
  redelijk: 0.6,
  vrij: 0.7,
  tamelijk: 0.7,
  nauwelijks: 0.3,
  ietwat: 0.5,
  licht: 0.6,
  half: 0.6,
  soort: 0.6,
};

/** Words that invert the polarity of a following term within a short window. */
export const NEGATORS = new Set([
  'niet',
  'geen',
  'nooit',
  'niets',
  'niks',
  'nergens',
  'zonder',
  'allesbehalve',
  'amper',
  'noch',
  'weinig',
]);

/**
 * Contrast markers. In "eerste helft prima, maar wat een drama daarna" the
 * clause after the marker carries the real verdict, so it is weighted up and
 * everything before it is weighted down.
 */
export const CONTRAST_MARKERS = new Set(['maar', 'echter', 'alleen', 'toch', 'desondanks', 'helaas']);

export const EMOJI: Record<string, number> = {
  '🔥': 2,
  '😍': 2.5,
  '💪': 2,
  '🐐': 3,
  '❤️': 2,
  '❤': 2,
  '👏': 2,
  '🙌': 2,
  '🎉': 2.25,
  '🏆': 2.5,
  '⚽': 0.5,
  '✅': 1,
  '😡': -2.5,
  '🤬': -3,
  '🤮': -3,
  '💩': -3,
  '😭': -2,
  '😢': -1.75,
  '🤡': -2.5,
  '🙈': -1.5,
  '😴': -1.5,
  '🤦': -2.25,
  '🤷': -1,
  '❌': -1,
  '📉': -1.75,
  '📈': 1.75,
};

/**
 * Sarcasm tells. Dutch football commentary is drenched in irony, and irony is
 * where a lexicon fails hardest — "geweldig hoor, weer zo'n briljante wissel"
 * scores +3 on its face. These markers do not attempt to score the sarcasm;
 * they flag the document as ambiguous so the optional LLM pass re-reads it.
 */
export const SARCASM_MARKERS = [
  /\bhoor\b/i,
  /\bnatuurlijk weer\b/i,
  /\bweer eens\b/i,
  /\balweer\b/i,
  /\bhoe verrassend\b/i,
  /\bwat een verrassing\b/i,
  /\bja hoor\b/i,
  /\btuurlijk\b/i,
  /\/s(?:\b|$)/,
  /\bironisch\b/i,
  /😏|🙄|😑/,
];
